version: '2'
services:
  jenkins:
    build: jenkins
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-registry
    ports:
      - "80:80"
      - "8081:8081"
      - "443:443"
